openapi: 3.0.1
servers:
  - url: https://api.malga.io
    description: Production
info:
  version: '0.1'
  title: Sessions
tags:
  - name: Sessions
    description: |

      Using sessions API it's possible to create an order, with items, payment methods and more, that can be payed through an endpoint or integrated to MalgaCheckout.

      # Creating and paying a session
      - Create a `session` informing the minimum required data
      - Using the `publicKey` returned by the creation or got by the details endpoint on `X-Api-Key` to authorize the payment 

      **Basic data of a session object**

      <SchemaDefinition schemaRef="#/components/schemas/Session" exampleRef="#/components/examples/Session" />
paths:
  /v1/sessions:
    post:
      summary: Create new session
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequest'
            example:
              $ref: '#/components/examples/SessionRequest/value'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
              example:
                $ref: '#/components/examples/SessionResponse/value'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Sessions
  /v1/sessions/{id}:
    get:
      summary: Get session details
      operationId: getSessionById
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
              example:
                $ref: '#/components/examples/SessionResponse/value'
      tags:
        - Sessions
    patch:
      summary: Update session status
      operationId: updateSession
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
              example:
                $ref: '#/components/examples/SessionResponse/value'
      tags:
        - Sessions
  /v1/sessions/{id}/charge:
    post:
      summary: Pay session
      operationId: paySession
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionChargeRequest'
            examples:
              - $ref: '#/components/examples/ChargeCardRequest'
              - $ref: '#/components/examples/ChargePixRequest'
              - $ref: '#/components/examples/ChargeBoletoRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionChargeResponse'
              examples:
                - $ref: '#/components/examples/SessionChargeCardResponse'
                - $ref: '#/components/examples/SessionChargePixResponse'
                - $ref: '#/components/examples/SessionChargeBoletoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Sessions
  /v1/sessions/{id}/cancel:
    post:
      summary: Cancel session
      operationId: cancelSession
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelSessionResponse'
              example:
                $ref: '#/components/examples/CancelSessionResponse/value'
      tags:
        - Sessions
  /v1/sessions/{id}/history:
    get:
      summary: Recover session history
      operationId: getSessionHistory
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionHistoryResponse'
      tags:
        - Sessions
  /v1/sessions/{id}/link:
    get:
      summary: Recover session with company settings
      operationId: getSessionWithSettings
      parameters:
        - name: id
          required: true
          description: Session ID
          in: path
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionSettingsResponse'
      tags:
        - Sessions

security:
  - X-Client-ID: []
    X-Api-Key: []
components:
  securitySchemes:
    X-Client-ID:
      type: apiKey
      in: header
      name: X-Client-Id
    X-Api-Key:
      type: apiKey
      in: header
      name: X-Api-Key
  schemas:
    ErrorResponse:
      properties:
        error:
          type: object
          allOf:
            - $ref: '#/components/schemas/ErrorItem'
    ErrorItem:
      properties:
        type:
          type: string
          enum:
            - api_error
            - bad_request
            - invalid_request_error
            - card_declined
            - conflict
        code:
          type: string
          description: Código de retorno da erro
        declinedCode:
          type: string
          description: Código de retorno da transação em caso de falha na autorização
        message:
          type: string
          description: Descrição breve do erro
        details:
          type: array
          description: Lista contendo objetos que detalham o erro de validação
      required:
        - type
    PaymentMethodCard:
      type: object
      properties:
        paymentType:
          type: string
          enum:
            - credit
            - debit
          description: Credit/Debit card charge method
        installments:
          type: integer
          description: Installments quantity for credit payments
      required:
        - paymentType
    PaymentMethodPix:
      properties:
        paymentType:
          type: string
          enum:
            - pix
          description: Pix charge, the source must be a valid customer
        expiresIn:
          type: integer
          description: Time in seconds that defines the validity of the charge
      required:
        - paymentType
        - expiresIn
    PaymentMethodBoleto:
      properties:
        paymentType:
          type: string
          enum:
            - boleto
          description: Boleto charge, the source must be a valid customer.
        expiresDate:
          type: string
          description: Boleto due date, ISO-Date, ex 2017-01-31
        instructions:
          type: string
          description: Boleto instructions field. Maximum 255 characters. Use \n for line break
        interest:
          type: object
          description: Optional informations of the fees for delay payment
          properties:
            days:
              type: integer
              description: Days after the expiration of the boleto when interest must be charged
            amount:
              type: integer
              description: Amount in cents of the interest rate that will be charged peer day
            percentage:
              type: number
              description: Amount in percentage of the interest rate that will be charged peer month
        fine:
          type: object
          description: Optional information of the fine condition for delay payment
          properties:
            days:
              type: integer
              description: Days after the boleto expiration when the fine must be charged
            amount:
              type: integer
              description: Fine amount in cents
            percentage:
              type: number
              description: Fine amount in percentage
      required:
        - paymentType
    UpdateSessionResponse:
      properties:
        id:
          type: string
          description: Session ID
        isActive:
          type: boolean
          description: Whether the session is active
    CancelSessionResponse:
      properties:
        id:
          type: string
          description: Session ID
        status:
          type: string
          enum:
            - created
            - paid
            - canceled
            - voided
          description: Session status
    SessionRequest:
      properties:
        orderId:
          type: string
          description: Unique identification of order in your side to help future conciliation
        amount:
          type: integer
          description: Transaction amount in cents, example 100 to charge R$ 1.00
        currency:
          type: string
          default: BRL
          description: Currency code to be used in charge, ISO 4217 format (see table of types)
        isActive:
          type: boolean
          description: Whether the session is active
        capture:
          type: boolean
          description: Whether the transaction should be captured automatically
        merchantId:
          type: string
          description: Merchant identification used in charge
        dueDate:
          type: string
          description: Session expiration date
        name:
          type: string
          description: Session name
        description:
          type: string
          description: Session description
        statementDescriptor:
          type: string
          description: Description to be displayed on the buyer's bank statement
        createLink:
          type: boolean
          description: Whether the session has a Payment Link
        paymentMethods:
          description: Payment methods available on this session
          anyOf:
            - $ref: '#/components/schemas/PaymentMethodCard'
            - $ref: '#/components/schemas/PaymentMethodPix'
            - $ref: '#/components/schemas/PaymentMethodBoleto'
        items:
          type: array
          description: Order items
          items:
            $ref: '#/components/schemas/SessionItemObject'
      required:
        - amount
        - name
        - merchantId
        - dueDate
        - paymentMethods
        - items
    SessionResponse:
      properties:
        id:
          type: string
          description: Session ID
        name:
          type: string
          description: Session name
        status:
          type: string
          enum:
            - created
            - paid
            - canceled
            - voided
          description: Session status
        isActive:
          type: boolean
          description: Whether the session is active
        clientId:
          type: string
          description: Client identification on Malga
        orderId:
          type: string
          description: Unique identification of order in your side to help future conciliation
        amount:
          type: integer
          description: Transaction amount in cents, example 100 to charge R$ 1.00
        currency:
          type: string
          description: Currency code to be used in charge, ISO 4217 format (see table of types)
        capture:
          type: boolean
          description: Whether the transaction should be captured automatically
        merchantId:
          type: string
          description: Merchant identification used in charge
        dueDate:
          type: string
          description: Session expiration date
        description:
          type: string
          description: Session description
        statementDescriptor:
          type: string
          description: Description to be displayed on the buyer's bank statement
        items:
          type: array
          description: Order items
          items:
            $ref: '#/components/schemas/SessionItemObject'
        paymentLink:
          type: string
          description: Link to access Payment Link of this session
        paymentMethods:
          type: array
          description: Payment methods available on this session
          anyOf:
            - $ref: '#/components/schemas/PaymentMethodCard'
            - $ref: '#/components/schemas/PaymentMethodPixResponse'
            - $ref: '#/components/schemas/PaymentMethodBoletoResponse'
        createdAt:
          type: string
          description: Created date
        updatedAt:
          type: string
          description: Updated date
        publicKey:
          type: string
          description: Access key with limited scope, must be used to pay the session
    PaymentMethodPixResponse:
      properties:
        paymentType:
          type: string
          enum:
            - pix
          description: método da cobrança via PIX, o source deve ser um customer válido.
        expiresIn:
          type: integer
          description: tempo em segundos que define a validade da cobrança.
        qrCodeData:
          type: string
          description: código copia e cola para o QR code dinâmico gerado, pronto para ser pago.
        qrCodeImageUrl:
          type: string
          description: link para download da imagem do QR code dinâmico gerado, pronto para ser scaneado e pago.
      required:
        - paymentType
        - expiresIn
        - qrCodeData
        - qrCodeImageUrl
    PaymentMethodBoletoResponse:
      properties:
        paymentType:
          type: string
          enum:
            - boleto
          description: método da cobrança via Boleto, o source deve ser um customer válido
        expiresDate:
          type: string
          description: data de vencimento do boleto em ISO-Date, ex 2017-01-31
        barcodeData:
          type: string
          description: código copia e cola do boleto registrado gerado, pronto para pagamento;
        barcodeImageUrl:
          type: string
          description: link para download do do boleto registrado gerado, pronto para pagamento;
      required:
        - paymentType
        - expiresDate
        - barcodeData
        - barcodeImageUrl
    SourceTypeCard:
      type: object
      description: identificação do merchant id a ser utilizado
      properties:
        sourceType:
          type: string
          description: tipo da origem da cobrança, usar `card` para cobrança em cartão tokenizado
          example: card
        cardId:
          type: string
          description: Identificador do cartão quando source tipo card (opcional)
      required:
        - sourceType
        - cardId
    SourceTypeCardOneShot:
      type: object
      description: identificação do merchant id a ser utilizado
      properties:
        sourceType:
          type: string
          description: tipo da origem da cobrança, usar `card` para cobrança em cartão tokenizado
          example: card
        card:
          type: object
          properties:
            cardHolderName:
              type: string
              description: Nome do portador do cartão
            cardNumber:
              type: string
              description: Número do cartão (Sem espaços)
            cardCvv:
              type: string
              description: Código de verificação
            cardExpirationDate:
              type: string
              description: Mês e ano de validade no formato MM/YYYY
      required:
        - sourceType
        - card
    SourceTypeToken:
      type: object
      properties:
        sourceType:
          type: string
          description: tipo da origem da cobrança, usar `token` para cobrança no token gerado
          example: token
        tokenId:
          type: string
          description: Identificador do token quando source tipo token (opcional)
      required:
        - sourceType
        - tokenId
    SourceTypeCustomer:
      type: object
      properties:
        sourceType:
          type: string
          description: tipo da origem da cobrança, usar `customer` para cobrança no cartão default do comprador
          example: customer
        customerId:
          type: string
          description: Identificador do cliente quando source tipo customer, debitando o cartão default do comprador
      required:
        - sourceType
        - customerId
    SourceTypeCustomerOneShot:
      type: object
      properties:
        sourceType:
          type: string
          description: tipo da origem da cobrança, usar `customer` para cobrança no cartão default do comprador
          example: customer
        customer:
          type: object
          properties:
            name:
              type: string
              description: nome do usuario
            email:
              type: string
              description: email do usuario
            phoneNumber:
              type: string
              description: telefone de contato do usuario
            document:
              allOf:
                - $ref: '#/components/schemas/Document'
            address:
              allOf:
                - $ref: '#/components/schemas/Address'
          required:
            - name
            - phoneNumber
            - email
            - document
      required:
        - sourceType
        - customer
    Address:
      type: object
      properties:
        country:
          type: string
          description: Padrão ISO 3166-1 alpha-2
        state:
          type: string
          description: Estado
        city:
          type: string
          description: Cidade
        district:
          type: string
          description: Bairro
        zipCode:
          type: string
          description: Codigo postal CEP
        street:
          type: string
          description: Nome da rua/avenida/travessa
        streetNumber:
          type: string
          description: Numero da rua
        complement:
          type: string
          description: Complemento caso exista
    Document:
      type: object
      properties:
        type:
          type: string
          description: tipo de documento, consultar tabela de tipos suportados
        number:
          type: string
          description: numero do documento formato conforme tipo selecionado
        country:
          type: string
          description: pais de emissão do documento, Padrão ISO 3166-1 alpha-2, consultar tabela de tipos suportados
          default: BR
    SessionItemObject:
      properties:
        name:
          type: string
          description: Session item name
        description:
          type: string
          description: Session item description
        unitPrice:
          type: number
          description: Item unit amount in cents, example 100 to charge R$ 1.00
        quantity:
          type: number
          description: Item quantity
        tangible:
          type: boolean
          description: Whether the item is tangible
    SessionHistoryResponse:
      type: array
      items:
        $ref: '#/components/schemas/SessionHistoryItem'
    SessionHistoryItem:
      type: object
      properties:
        status:
          type: string
          enum:
            - created
            - paid
            - canceled
            - voided
          description: Status da sessão
        id:
          type: string
          description: Session ID
        createdAt:
          type: string
          description: Created date
        updatedAt:
          type: string
          description: Updated date
    SessionSettingsResponse:
      properties:
        id:
          type: string
          description: Session ID
        name:
          type: string
          description: Session name
        status:
          type: string
          enum:
            - created
            - paid
            - canceled
            - voided
          description: Session status
        isActive:
          type: boolean
          description: Whether the session is active
        clientId:
          type: string
          description: Client identification on Malga
        orderId:
          type: string
          description: Unique identification of order in your side to help future conciliation
        amount:
          type: integer
          description: Transaction amount in cents, example 100 to charge R$ 1.00
        currency:
          type: string
          description: Currency code to be used in charge, ISO 4217 format (see table of types)
        capture:
          type: boolean
          description: Whether the transaction should be captured automatically
        merchantId:
          type: string
          description: Merchant identification used in charge
        dueDate:
          type: string
          description: Session expiration date
        description:
          type: string
          description: Session description
        statementDescriptor:
          type: string
          description: Description to be displayed on the buyer's bank statement
        items:
          type: array
          description: Order items
          items:
            $ref: '#/components/schemas/SessionItemObject'
        paymentLink:
          type: string
          description: Link to access Payment Link of this session
        paymentMethods:
          type: array
          description: Payment methods available on this session
          anyOf:
            - $ref: '#/components/schemas/PaymentMethodCard'
            - $ref: '#/components/schemas/PaymentMethodPixResponse'
            - $ref: '#/components/schemas/PaymentMethodBoletoResponse'
        createdAt:
          type: string
          description: Created date
        updatedAt:
          type: string
          description: Updated date
        publicKey:
          type: string
          description: Access key with limited scope, must be used to pay the session
        settings:
          type: object
          description: Company settings
          $ref: '#/components/schemas/UserSettings'
    UserSettings:
      properties:
        id:
          type: string
          format: uuid
          description: Company settings ID
        email:
          type: string
          format: email
          description: Company e-mail
        phone:
          type: string
          format: phone
          description: Company phone
        statementDescription:
          type: string
          description: Description to be displayed on buyer's invoice
        logo:
          type: string
          format: uri
          description: Company logo URL
        mainColor:
          type: string
          description: Main color
        secondaryColor:
          type: string
          description: Secondary color
        attentionColor:
          type: string
          description: Attention color
        errorColor:
          type: string
          description: Error message color
        successColor:
          type: string
          description: Success message color
        backgroundColor:
          type: string
          description: Background color
        companyName:
          type: string
          description: Company name
        clientId:
          type: string
          description: Client identification on Malga
        documentNumber:
          type: string
          description: Document number registered on company account
        language:
          type: string
          description: Default company language
    SessionChargeRequest:
      properties:
        customerId:
          type: string
          format: uuid
          description: Customer identification
        paymentMethod:
          description: Payment method to be used
          oneOf:
            - $ref: '#/components/schemas/PaymentMethodCard'
            - $ref: '#/components/schemas/PaymentMethodPix'
            - $ref: '#/components/schemas/PaymentMethodBoleto'
        paymentSource:
          oneOf:
            - $ref: '#/components/schemas/SourceTypeCard'
            - $ref: '#/components/schemas/SourceTypeCardOneShot'
            - $ref: '#/components/schemas/SourceTypeToken'
            - $ref: '#/components/schemas/SourceTypeCustomer'
            - $ref: '#/components/schemas/SourceTypeCustomerOneShot'
        fraudAnalysis:
          description: Additional parameters for fraud analysis, required by provider's anti-fraud
          allOf:
            - $ref: '#/components/schemas/FraudAnalysisRequest'
      required:
        - paymentMethod
        - paymentSource
    SessionChargeResponse:
      properties:
        id:
          type: string
          description: ChargeResponse ID
        clientId:
          type: string
          format: uuid
          description: Client identification on Malga
        merchantId:
          type: string
          format: uuid
          description: Merchant identification used in charge
        description:
          type: string
          description: Short description
        orderId:
          type: string
          description: Unique identification of order in your side to help future conciliation
        createdAt:
          type: string
          description: Created date
        amount:
          type: number
          description: Transaction amount in cents, example 100 to charge R$ 1.00
        originalAmount:
          type: number
          description: Transaction original amount in cents, example 100 to charge R$ 1.00
        currency:
          type: string
          description: Currency code to be used in charge, ISO 4217 format (see table of types)
          default: BRL
        statementDescriptor:
          type: string
          description: Description to be displayed on the buyer's bank statement
        status:
          type: string
          enum:
            - created
            - paid
            - canceled
            - voided
          description: Session status
        paymentMethod:
          oneOf:
            - $ref: '#/components/schemas/PaymentMethodCard'
            - $ref: '#/components/schemas/PaymentMethodPixResponse'
            - $ref: '#/components/schemas/PaymentMethodBoletoResponse'
        paymentSource:
          anyOf:
            - $ref: '#/components/schemas/SourceTypeCard'
            - $ref: '#/components/schemas/SourceTypeCardOneShot'
            - $ref: '#/components/schemas/SourceTypeToken'
            - $ref: '#/components/schemas/SourceTypeCustomer'
            - $ref: '#/components/schemas/SourceTypeCustomerOneShot'
        transactionRequests:
          type: array
          items:
            $ref: '#/components/schemas/TransactionRequest'
    TransactionRequest:
      properties:
        id:
          type: string
          description: unique identification of request on the provider
        providerId:
          type: string
          description: provider identification related to your merchant id
        providerType:
          type: string
          description: provider code, see table of supported providers
        idempotencyKey:
          type: string
          description: unique identification automatically created by Malga for each request, used to assure idempotency and avoid duplicity, could be used to get transactions in the provider's API or dashboard.
        authorizationNsu:
          type: string
          description: authorization number retunred by provider
          deprecated: true
        transactionId:
          type: string
          description: unique identification of transaction on provider, could be used to get transaction in the provider's API.
        requestType:
          type: string
          enum:
            - pending
            - authorization
            - pre_authorization
            - void
            - capture
            - probe
            - charge_back
            - zero_dollar
            - anti_fraud
          description: type of request performed on provider
        requestStatus:
          type: string
          enum:
            - running
            - failed
            - success
            - timeout
            - internal_error
            - processing
          description: status of request processing
        amount:
          type: integer
          description: transaction request amount sent to provider, for partial capture/refund the amount could be different from original transaction amount
        responseTs:
          type: string
          description: total spent time in request processing
        providerError:
          type: object
          description: transaction requet error details
          properties:
            message:
              type: string
              description: error message mapped by Malga that describes declined reason
            declinedCode:
              type: string
              description: error code mapped by plyg based in the declined code returned by provider
            retryable:
              type: boolean
              description: declined code can be or not retried
            networkDeniedReason:
              type: string
              description: declined code returned as is from the provider, check in the provider's documentation
            networkDeniedMessage:
              type: string
              description: declined message returned as is from the provider
        providerAuthorization:
          type: object
          description: additional data returned by provider
          properties:
            networkAuthorizationCode:
              type: string
              description: authorization code as returned by provider
            networkResponseCode:
              type: string
              description: response code as returned by provider
        createdAt:
          type: string
          description: Created date of request
        updatedAt:
          type: string
          description: Updated date of request
    FraudAnalysisRequest:
      properties:
        customer:
          description: customer (payeer) data
          type: object
          properties:
            name:
              type: string
              description: customer name
            email:
              type: string
              description: customer email
            phone:
              type: string
              description: customer phone number
            identityType:
              type: string
              description: document type, see table of types
            identity:
              type: string
              description: document number
            registrationDate:
              type: string
              description: customer registration date
            deliveryAddress:
              description: Delivery customer address
              allOf:
                - $ref: '#/components/schemas/FraudAnalysisAddress'
            billingAddress:
              description: Billing customer address
              allOf:
                - $ref: '#/components/schemas/FraudAnalysisAddress'
            browser:
              description: information about customer browser
              allOf:
                - $ref: '#/components/schemas/FraudAnalysisCustomerBrowser'
        cart:
          description: Cart of products details
          type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: product name
                  quantity:
                    type: integer
                    description: itens of product purchased
                  sku:
                    type: string
                    description: unique product identification on store
                  unitPrice:
                    type: integer
                    description: unit price of product in cents
                  risk:
                    type: string
                    enum:
                      - high
                      - low
                    description: product risk of fraud
                  description:
                    type: string
                    description: product description
                  categoryId:
                    type: string
                    description: category which product belongs to
        device:
          description: Customer device details
          type: object
          properties:
            os:
              type: object
              properties:
                type:
                  type: string
                  description: Operational system type
                version:
                  type: string
                  description: Operational system version
            model:
              type: string
              description: Device model
            ramCapacity:
              type: integer
              description: Device ram capacity
            diskCapacity:
              type: integer
              description: Device disk capacity
            freeDiskSpace:
              type: integer
              description: Device disk space still free
            resolution:
              type: integer
              description: Device resolution
            vendors:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Vendor attribute name
                  value:
                    type: string
                    description: Vendor attribute value
            vendorAttributes:
              description: Device attributes by vendor
              type: object
              properties:
                flash:
                  type: boolean
                  description: Device has flash
                phoneCalls:
                  type: boolean
                  description: Device can make phone calls
                sendSms:
                  type: boolean
                  description: Device can send sms
                videoCamera:
                  type: boolean
                  description: Device has video camera
                cpuCount:
                  type: integer
                  description: Device cpu count
                simulator:
                  type: boolean
                  description: Device has simulator
                language:
                  type: string
                  description: Device language
                idiom:
                  type: string
                  description: Device idiom
                platform:
                  type: string
                  description: System platform
                name:
                  type: string
                  description: Device name
                family:
                  type: string
                  description: Device family
                retinaDisplay:
                  type: boolean
                  description: Device has retina display
                camera:
                  type: boolean
                  description: Device has camera
                model:
                  type: string
                  description: Device model
                frontCamera:
                  type: boolean
                  description: Device has front camera
    FraudAnalysisAddress:
      type: object
      properties:
        country:
          type: string
          description: formated in ISO 3166-1 alpha-2
        state:
          type: string
          description: address state
        city:
          type: string
          description: address city
        district:
          type: string
          description: address district or neighboor
        zipCode:
          type: string
          description: zip code
        street:
          type: string
          description: street address
        number:
          type: string
          description: street number address
        complement:
          type: string
          description: apartament number or address complement
    FraudAnalysisMetadata:
      type: object
      properties:
        customer:
          description: customer (payeer) data
          type: object
          properties:
            name:
              type: string
              description: customer name
            email:
              type: string
              description: customer email
            phone:
              type: string
              description: customer phone number
            identityType:
              type: string
              description: document type, see table of types
            identity:
              type: string
              description: document number
            registrationDate:
              type: string
              description: customer registration date
            deliveryAddress:
              description: Endereço de entrega
              allOf:
                - $ref: '#/components/schemas/FraudAnalysisAddress'
            billingAddress:
              description: Endereço de cobrança
              allOf:
                - $ref: '#/components/schemas/FraudAnalysisAddress'
        cart:
          description: Cart of products details
          type: object
          properties:
            items:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: product name
                  quantity:
                    type: integer
                    description: itens of product purchased
                  sku:
                    type: string
                    description: unique product identification on store
                  unitPrice:
                    type: integer
                    description: unit price of product in cents
                  risk:
                    type: string
                    enum:
                      - high
                      - low
                    description: product risk of fraud
                  description:
                    type: string
                    description: product description
                  categoryId:
                    type: string
                    description: category which product belongs to
    FraudAnalysisCustomerBrowser:
      type: object
      properties:
        browserFingerprint:
          type: string
          description: fingerprint id generated by browser
        cookiesAccepted:
          type: boolean
          description: indicates if cookies has been accepeted
        email:
          type: string
          description: logged email address
        hostName:
          type: string
          description: user's computer hostname
        ipAddress:
          type: string
          description: user's ip address
        type:
          type: string
          description: browser's user-agent
  examples:
    SessionResponse:
      value:
        id: c1db83fa-723c-4e1f-9722-bc19d1be6791
        name: Pedido 1
        status: created
        isActive: true
        clientId: 39d2d314-5412-431a-b34b-74f9f0fbe7e1
        orderId: b84b7694-d22f-4083-bee7-c1274b16eb4a
        amount: 100
        currency: BRL
        capture: true
        merchantId: 9930c8d9-a7a8-4039-9faf-3715ad87baf8
        dueDate: '2022-10-26T19:32:08.000Z'
        description: Pedido Black Friday
        statementDescriptor: LOJA JOAO
        items:
          - name: Item 1
            description: Item do carrinho
            unitPrice: 1000
            quantity: 1
            tangible: false
        paymentLink: https://link.malga.io/c1db83fa-723c-4e1f-9722-bc19d1be6791
        paymentMethods:
          - paymentType: pix
            expiresIn: 30
        createdAt: '2022-10-25T22:49:06.588Z'
        updatedAt: '2022-10-25T22:49:06.588Z'
        publicKey: 8be71cdf-01dc-4b1a-823a-4c58be6e4cf1
    SessionRequest:
      value:
        amount: 100
        isActive: true
        capture: true
        merchantId: 1b0c6960-702a-4074-95c2-eed2790c16a1
        dueDate: '2022-10-25T09:28:45.000Z'
        description: Promoção Black Friday
        statementDescriptor: LOJA JOAO
        paymentMethods:
          - paymentType: pix
            expiresIn: 30
        items:
          - name: Item 1
            description: Item do carrinho
            unitPrice: 1000
            quantity: 1
            tangible: false
    Session:
      value:
        id: 1b0c6960-702a-4074-95c2-eed2790c16a1
        name: Nome da sessão
        status: created
        isActive: true
        clientId: 1b0c6960-702a-4074-95c2-eed2790c16a1
        orderId: null
        amount: 100
        currency: BRL
        capture: true
        merchantId: 69aea152-ba70-49a3-a31c-044ac1651146
        dueDate: '2022-10-25T09:28:45.000Z'
        description: Promoção Black Friday
        statementDescriptor: LOJA JOAO
        paymentMethods:
          - paymentType: credit
            installments: 1
        items:
          - id: 78601913-a176-4d71-b7e8-abb6fc49a340
            name: Item 1
            description: Descrição do item
            unitPrice: 10000
            quantity: 1
            tangible: false
        createdAt: '2022-10-25T09:28:45.000Z'
        updatedAt: '2022-10-25T09:28:45.000Z'
        publicKey: 1b0c6960-702a-4074-95c2-eed2790c16a1
    ErrorResponse:
      value:
        error:
          type: card_declined
          declinedCode: invalid_number
          message: invalid card number
        UpdateSessionResponse:
    CancelSessionResponse:
      value:
        id: c1db83fa-723c-4e1f-9722-bc19d1be6791
        status: canceled